#!/bin/sh -e

$NFT add table t

# pass for non-existent flowtable
$NFT destroy flowtable t f

# successfully delete existing flowtable
$NFT add flowtable t f '{ hook ingress priority 10; devices = { lo }; }'
$NFT destroy flowtable t f
