#!/bin/bash

set -e

RULESET="table ip t {
	set s {
		type ipv4_addr . inet_proto . inet_service
		flags interval
		counter
		elements = { 1.0.0.1 . udp . 53 }
	}
}"

$NFT -f - <<< $RULESET

$NFT delete element t s { 1.0.0.1 . udp . 53}

exit 0
